export const merchantCategoryCodes = {
  '0742': 'Veterinary Services',
  '0763': 'Agricultural Cooperative',
  '0780': 'Horticultural Services',
  '1520': 'General Contractors – Residential and Commercial',
  '1711': 'Heating, Plumbing, and Air Conditioning Contractors',
  '1731': 'Electrical Contractors',
  '1740': 'Masonry, Stonework, and Plastering Contractors',
  '1750': 'Carpentry Contractors',
  '1761': 'Roofing and Siding Contractors',
  '1771': 'Concrete Work Contractors',
  '1799': 'Special Trade Contractors (Not Elsewhere Classified)',
  '2741': 'Miscellaneous Publishing and Printing',
  '2791': 'Typesetting, Plate Making, and Related Services',
  '2842': 'Specialty Cleaning – Polishes, Sanitation Goods',
  '3000': 'United Airlines',
  '3351': 'Carpentry Materials and Supplies',
  '3501': 'Office Furniture',
  '4111': 'Local and Suburban Commuter Passenger Transportation, including Ferries',
  '4112': 'Passenger Railways',
  '4121': 'Taxicabs and Limousines',
  '4131': 'Bus Lines',
  '4214': 'Motor Freight Carriers and Trucking',
  '4511': 'Airlines, Air Carriers',
  '4722': 'Travel Agencies and Tour Operators',
  '4789': 'Transportation Services (Not Elsewhere Classified)',
  '4812': 'Telecommunication Equipment and Telephone Sales',
  '4814': 'Telecommunication Services',
  '4899': 'Cable, Satellite, and Other Pay Television and Radio Services',
  '4900': 'Utilities – Electric, Gas, Water, Sanitary',
  '5045': 'Computers, Peripherals, and Software',
  '5046': 'Commercial Equipment (Not Elsewhere Classified)',
  '5047': 'Medical, Dental, Ophthalmic, and Hospital Equipment and Supplies',
  '5051': 'Metal Service Centers and Offices',
  '5099': 'Durable Goods (Not Elsewhere Classified)',
  '5111': 'Stationery, Office Supplies, Printing and Writing Paper',
  '5131': 'Piece Goods, Notions, and Other Dry Goods',
  '5137': 'Men’s, Women’s, and Children’s Uniforms and Commercial Clothing',
  '5139': 'Commercial Footwear',
  '5192': 'Books, Periodicals, and Newspapers',
  '5211': 'Lumber and Building Materials Stores',
  '5231': 'Glass, Paint, Wallpaper Stores',
  '5251': 'Hardware Stores',
  '5261': 'Nurseries, Lawn and Garden Supply Stores',
  '5300': 'Wholesale Clubs',
  '5309': 'Duty Free Stores',
  '5311': 'Department Stores',
  '5331': 'Variety Stores',
  '5399': 'Miscellaneous General Merchandise',
  '5411': 'Supermarkets, Grocery Stores',
  '5499': 'Miscellaneous Food Stores',
  '5532': 'Automotive Tire Stores',
  '5533': 'Automotive Parts and Accessories Stores',
  '5541': 'Service Stations (with or without ancillary services)',
  '5611': 'Men’s and boy’s Clothing and Accessories Stores',
  '5621': 'Women’s Ready-to-Wear Stores',
  '5631': 'Women’s Accessory and Specialty Shops',
  '5641': 'Children’s and Infant’s Wear Stores',
  '5651': 'Family Clothing Stores',
  '5661': 'Shoe Stores',
  '5691': 'Men’s and Women’s Clothing Stores',
  '5699': 'Miscellaneous Apparel and Accessory Shops',
  '5732': 'Electronics Stores',
  '5733': 'Music Stores – Musical Instruments, Pianos, Sheet Music',
  '5734': 'Computer Software Stores',
  '5811': 'Caterers',
  '5812': 'Eating Places and Restaurants',
  '5813':
    'Drinking Places (Alcoholic Beverages), Bars, Taverns, Cocktail lounges, Nightclubs and Discotheques',
  '5814': 'Fast Food Restaurants',
  '5912': 'Drug Stores and Pharmacies',
  '5921': 'Package Stores – Beer, Wine, and Liquor',
  '5931': 'Used Merchandise Stores – Secondhand Stores',
  '5932': 'Antique Shops – Sales, Repairs, and Restoration Services',
  '5940': 'Bicycle Shops – Sales and Service',
  '5941': 'Sporting Goods Stores',
  '5942': 'Book Stores',
  '5943': 'Stationery Stores, Office and School Supply Stores',
  '5944': 'Watch, Clock, Jewelry, and Silverware Stores',
  '5945': 'Hobby, Toy, and Game Shops',
  '5946': 'Camera and Photographic Supply Stores',
  '5947': 'Card Shops, Gift, Novelty, and Souvenir Shops',
  '5948': 'Luggage and Leather Goods Stores',
  '5964': 'Direct Marketing – Catalog Merchant',
  '5969': 'Direct Marketing – Other',
  '5977': 'Cosmetic Stores',
  '5992': 'Florists',
  '5995': 'Pet Shops, Pet Foods, and Supplies Stores',
  '5999': 'Miscellaneous and Specialty Retail Stores',
  '6011': 'Financial Institutions – Manual Cash Disbursements',
  '6012': 'Financial Institutions – Merchandise and Services',
  '6051': 'Non-Financial Institutions – Foreign Currency, Money Orders (Not Wire Transfer)',
  '6211': 'Security Brokers and Dealers',
  '7011':
    'Lodging – Hotels, Motels, Resorts, Central Reservation Services (not elsewhere classified)',
  '7211': 'Laundry Services - Family and Commercial',
  '7216': 'Dry Cleaners',
  '7298': 'Health and Beauty Shops',
  '7399': 'Business Services (Not Elsewhere Classified)',
  '7512': 'Car Rental Agencies',
  '7523': 'Parking Lots and Garages',
  '7832': 'Motion Picture Theaters',
  '7841': 'Video Tape Rental Stores',
  '7922': 'Theatrical Producers (Except Motion Pictures), Ticket Agencies',
  '7996': 'Amusement Parks, Carnivals, Circuses, Fortune Tellers',
  '8011': 'Doctors and Physicians – Not Elsewhere Classified',
  '8021': 'Dentists and Orthodontists',
  '8043': 'Opticians, Optical Goods, and Eyeglasses',
  '8049': 'Chiropractors',
  '8050': 'Nursing and Personal Care Facilities',
  '8062': 'Hospitals',
  '8099': 'Medical Services and Health Practitioners (Not Elsewhere Classified)',
}
